spring:
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 465
    username: divyaojha792@gmail.com
    password: hevdptvoedhiaqez
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com


  cloud:
    function:
      definition: orderCreated
    stream:
      function:
        definition: orderCreated
      bindings:
        orderCreated-in-0:
          destination: order.exchange
          group: notification-group
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092


server:
  port: 8088