spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: divyaojha
    password: divyaojha
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


#logging:
#  level:
#    root: INFO
#  file:
#    name: logs/app.log
#  logback:
#    rollingpolicy:
#      max-file-size: 5MB
#      max-history: 7



server:
  port: 8082